### ISSUE TITLE
update list of resources (JSON on server) from Zotero library.

### ISSUE THREAD

**Issue by sharafeddeen** [StatisticsHelper/statistics-helper#14]
Problem: whenever resources are updated on Zotero library, it's not reflected on the server's JSON file of resources.

Solution:
  1) check out the bash script used to run the Pyzotero API call, then
  2) see if you can automate that call once a day or whenever the library is updated.

Notes:
  - it's probably easier to update the JSON file once a day because it doesn't require knowing when the library is updated.

**Comment by baeolophus** [comment]
If we don't have time for this before the hours run out, please write up how to do this manually: https://osf.io/zbkux/wiki/Instructions%20for%20updating%20and%20running%20web%20server/
